---
version: "3"
services:
  squidproxyserver:
    network_mode: host
    environment:
      TZ: Europe/Amsterdam
    container_name: "squidproxyserver"
    hostname: squidproxyserver
    build:
      context: .
      dockerfile: myDockerfile_squidproxyserver
    pull_policy: always
    restart: unless-stopped
    volumes:
      - "/home/pi/docker-containers/proxy-server/squid.conf:/etc/squid/squid.conf"
      - "/home/pi/docker-containers/proxy-server/cache:/var/cache/squid"
      - "/home/pi/docker-containers/proxy-server/log:/var/log/squid"
